### PR TITLE
Fix python bindings

### LINKED ISSUE #63: Python bindings not compiling anymore
The latest CMAKE changes break my Python setup (as already written by @robertodr in #59). 

I am working on fixing the problems (should be done soon). Opening this issue in case there is anything to discuss.

### PR DESCRIPTION
**Pull request by chjacob-tubs**
This is my attempt at getting the SWIG Python bindings back to work. It does the job for me, but I am sure the setup is not perfect (maybe a cmake expert can have a look, see "possible improvements" below). (Mostly fixes #63)

##Changes:
- Adjusted paths to include files etc.
- Removed unnecassary / auto-generated files
- Use static linking for Python module

##Possible improvements:
- I am sure the cmake setup can be improved. Apparently, there is a UseSWIG module now that could simplify things (but I didnt get it to work)
- Linking of the Python module to the dynamic library is not working, as the paths are not set correctly. This seems to be related to getting the RPATH set correctly, which seems to be difficult especially on MacOS. (I dont want to set another (DY)LD_LIBRARY_PATH only to get the Python module to work)
- The "make install" step is required to get a working python module (in the prefix/python directory). In the build directory, the file "xcfun.py" is missing. Dont know how to tell cmake to copy it there (or what the correct way of handling this is)

### CODE REVIEW

**Comment by robertodr** [comment]
I am not familiar enough with SWIG to give comments off the top of my head. I'll check out this branch locally, test it out and give a more informed review.

File: api/xcfun.h [hunk 1]
```diff
@@ -14,9 +14,12 @@
 
 #pragma once
 
+#ifndef SWIG
```
Comment (robertodr) [inline api/xcfun.h]: I tried removing this one, because I think we should keep this file as clean as possible from preprocessor macros and `ifdef`-s. Unfortunately the way SWIG works (in my limited experiments) makes it absolutely necessary.

Comment (robertodr) [inline api/xcfun.h]: I tried removing this one, because I think we should keep this file as clean as possible from preprocessor macros and `ifdef`-s. Unfortunately the way SWIG works (in my limited experiments) makes it absolutely necessary.

File: python/CMakeLists.txt [hunk 2]
```diff
@@ -28,7 +28,7 @@ add_custom_command(
   COMMAND ${PYTHON_EXECUTABLE}
   ARGS "setup.py" "build_ext" "--inplace"
   WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
-  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/setup.py ${CMAKE_CURRENT_BINARY_DIR}/xcfun_swigPYTHON_wrap.c
+  DEPENDS xcfun-static ${CMAKE_CURRENT_BINARY_DIR}/setup.py ${CMAKE_CURRENT_BINARY_DIR}/xcfun_swigPYTHON_wrap.c
```
Comment (robertodr) [inline python/CMakeLists.txt]: I tried finding a fix for the shared library, but the way SWIG works (in my limited playing around) again makes it impossible. The `RPATH` on the generated DSO/executable can be fixed by CMake with an easy command, but the problem here is that SWIG takes ownership of this build and CMake know nothing about this target to handle `RPATH`.

File: python/CMakeLists.txt [hunk 3]
```diff
@@ -9,7 +9,7 @@ set(XCFUN_SWIG_WRAP "xcfun_swigPYTHON_wrap.c")
 add_custom_command(
   OUTPUT ${XCFUN_SWIG_WRAP}
   COMMAND "${SWIG_EXECUTABLE}"
-  ARGS "-python" "-I${PROJECT_SOURCE_DIR}/include" "-outdir" "${CMAKE_CURRENT_BINARY_DIR}" "-o" ${XCFUN_SWIG_WRAP} ${XCFUN_SWIG}
+  ARGS "-python" "-I${CMAKE_BINARY_DIR}/include" "-I${PROJECT_SOURCE_DIR}/api" "-outdir" "${CMAKE_CURRENT_BINARY_DIR}" "-o" ${XCFUN_SWIG_WRAP} ${XCFUN_SWIG}
```
Comment (robertodr) [inline python/CMakeLists.txt]: Apparently SWIG takes over completely the build of this wrapper DSO. Hence I cannot fix the `RPATH` using CMake (which would be one line of CMake). Plus, SWIG uses GCC no matter what compiler was used to build XCFun. The latter is not a problem (I think?) but is certainly worrisome. Until we explore pybind11 in a little more detail this will have to do.

File: python/CMakeLists.txt [hunk 4]
```diff
@@ -28,7 +28,7 @@ add_custom_command(
   COMMAND ${PYTHON_EXECUTABLE}
   ARGS "setup.py" "build_ext" "--inplace"
   WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
-  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/setup.py ${CMAKE_CURRENT_BINARY_DIR}/xcfun_swigPYTHON_wrap.c
+  DEPENDS xcfun-static ${CMAKE_CURRENT_BINARY_DIR}/setup.py ${CMAKE_CURRENT_BINARY_DIR}/xcfun_swigPYTHON_wrap.c
   )
```
Comment (robertodr) [inline python/CMakeLists.txt]: To avoid the install step you will need to copy `xcfun.py` to `${CMAKE_CURRENT_BINARY_DIR}`:
```
file(COPY xcfun.py DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
```
should do it. The install path will probably have to be reworked at a later stage.

**Comment by robertodr** [comment]
Apologies that it took quite a bit to review this one. Being in another timezone did not compose well with being unfamiliar with SWIG. Still, great learning opportunity for me!

**Comment by chjacob-tubs** [comment]
I put some more work into this and now used UseSWIG instead of the manual setup that was used before. Please have a look, I think this is much nicer now. However, I didnt the RPATH stuff to work so I am still linking to the static library. To me, this is not a problem, but maybe you want to fix that.

I tested on MacOS and Linux with gcc. I am not sure whether switching to a different compiler will cause problems when building the Python shared library, because the Python libraries are usually built with gcc.

I also fixed the copying part, so the xcfun Python module can be used directly from the build directory.

File: api/xcfun.h (hunk 1 above)
Comment (chjacob-tubs) [reply api/xcfun.h]: Agree, but I think there is indeed no other way.

File: python/CMakeLists.txt (hunk 2 above)
Comment (chjacob-tubs) [reply python/CMakeLists.txt]: See my comment below, now CMake is in the driver seat, so possibly the RPATH stuff can be fixed.

File: python/CMakeLists.txt (hunk 3 above)
Comment (chjacob-tubs) [reply python/CMakeLists.txt]: Again, now CMake is in charge, but I am not sure whether this is a good or bad thing. In this step, one has to link against the Python libraries these are usually built with gcc. So switching to another compiler might cause problems here, but didnt test other compilers.

File: cmake/custom/FindPythonLibsNew.cmake [hunk 5]
```diff
@@ -1,195 +0,0 @@
-# - Find python libraries
```
Comment (robertodr) [inline cmake/custom/FindPythonLibsNew.cmake]: This file should be kept. It comes from pybind11 and it's the only CMake `Find`-package (that i know of) that will find a consistent version of interpreter and libraries on your machine. The stock `FindPythonLIbs.cmake` can (and will, given the chance!) get you a library that has nothing to do with your interpreter. Please restore this file and use `find_package(PythonLibsNew 2.7 REQUIRED)` instead of the `find_package(PythonInterp 2.7 REQUIRED)` and `find_package(PythonLibs 2.7 REQUIRED)`

File: python/CMakeLists.txt [hunk 6]
```diff
@@ -1,38 +1,34 @@
-set(Python_ADDITIONAL_VERSIONS 3.7 3.6 3.5)  # adjust with CMake minimum FindPythonInterp
-find_package(PythonLibsNew 2.7 REQUIRED)
 find_package(SWIG REQUIRED)
+INCLUDE(UseSWIG)
```
Comment (robertodr) [inline python/CMakeLists.txt]: Nit-pick: @bast and I prefer CMake commands in lowercase, _e.g._ `include(UseSWIG)`

File: python/CMakeLists.txt [hunk 7]
```diff
@@ -1,38 +1,34 @@
...
+
+find_package(PythonInterp 2.7 REQUIRED)
```
Comment (robertodr) [inline python/CMakeLists.txt]: See my comments above about finding Python interpreter and libraries.

File: python/CMakeLists.txt [hunk 8]
```diff
@@ -1,38 +1,34 @@
...
-  COMMAND "${SWIG_EXECUTABLE}"
-  ARGS "-python" "-I${PROJECT_SOURCE_DIR}/include" "-outdir" "${CMAKE_CURRENT_BINARY_DIR}" "-o" ${XCFUN_SWIG_WRAP} ${XCFUN_SWIG}
-  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
-  DEPENDS XCFun ${XCFUN_SWIG}
-  )
+set_property(SOURCE "${XCFUN_SWIG}" PROPERTY SWIG_FLAGS "-I${CMAKE_BINARY_DIR}/include" 
+                                                        "-I${PROJECT_SOURCE_DIR}/api")
+set_property(SOURCE "${XCFUN_SWIG}" PROPERTY SWIG_OUTDIR ${CMAKE_CURRENT_BINARY_DIR})
+
+# requires CMake 3.8
```
Comment (robertodr) [inline python/CMakeLists.txt]: I'm not against moving to CMake 3.8, but that probably requires larger consensus.

File: python/CMakeLists.txt [hunk 9]
```diff
@@ -1,38 +1,34 @@
...
+#swig_add_library(xcfun_swig LANGUAGE python SOURCES "${XCFUN_SWIG}")
+swig_add_module(xcfun_swig python "${XCFUN_SWIG}")
 
-configure_file(
-  ${CMAKE_CURRENT_LIST_DIR}/setup.py.in
-  ${CMAKE_CURRENT_BINARY_DIR}/setup.py
-  )
+target_include_directories(${SWIG_MODULE_xcfun_swig_REAL_NAME} 
+                           PRIVATE ${PYTHON_INCLUDE_DIRS}
+                                   ${NUMPY_INCLUDE_DIRS}
```
Comment (robertodr) [inline python/CMakeLists.txt]: Is this needed?

File: python/CMakeLists.txt (hunk 8 above)
Comment (bast) [reply python/CMakeLists.txt]: For me it is OK if the bindings need 3.8 but the configuration should not die if CMake is below 3.8 for those who configure without the bindings.

Comment (chjacob-tubs) [reply python/CMakeLists.txt]: The current code works with CMake below 3.5, the version that requires CMake 3.8 is commented out. Lets leave it like this and change the code to commented version once a newer CMake is required anyways.

**Comment by chjacob-tubs** [comment]
Sorry for removing FinfPythonLibsNew - I thought that was something obscure that I added at some point. I stand corrected. The target_include_directories is indeed required, but I made the linking part a bit nicer

**Comment by robertodr** [comment]
@bast I think once this is in we can:
1. Branch off `release/v.2.0`
2. Officially tag `v2.0.0`

**Comment by chjacob-tubs** [comment]
@robertodr @bast Let me fix the Python tests (#43) before doing the v2.0 release.

**Comment by robertodr** [comment]
Oh yes, of course! Thanks for reining in my enthusiasm :) Merging this one and closing #67
